---
title: "Class 05: Data Visualization with GGPLOT"
author: "Alice Lai  PID:A16799081"
date: "4/16/2024"
format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---

## Cars data ggplot 
```{r}
##install.packages("ggplot2")
library(ggplot2)

ggplot(cars)

ggplot(cars) +
  aes(x=speed, y=dist)
  
ggplot(cars) +
  aes(x=speed, y=dist) +
  geom_point()

x <- ggplot(cars) +
  aes(x=speed, y=dist) +
  geom_point()
  
x + geom_line()

x + geom_smooth()

x + geom_smooth(method = "lm", se = FALSE)

x + geom_smooth(method = "lm", se = FALSE) + 
  labs (title = "Stopping Distance vs. Speed",
          x = "Speed (MPH)", 
          y = "Stopping Distance (ft)") +
  theme_bw()
   
```


## Anti-viral drug data analysis
```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)

nrow(genes)

colnames(genes)
ncol(genes)

table(genes$State)
round( table(genes$State)/nrow(genes) * 100, 2 )
```


## Anti-viral drug data ggplot
```{r}
ggplot(genes) + 
    aes(x=Condition1, y=Condition2) +
    geom_point() 

p <- ggplot(genes) + 
    aes(x=Condition1, y=Condition2, col=State) +
    geom_point() 

p + scale_colour_manual( values=c("blue","gray","red") )

p + scale_colour_manual( values=c("blue","gray","red") ) + 
  labs(title = "Gene Expression Changes Upon Drug Treatment",
          x = "Control (no drug)", 
          y = "Drug Treatment")
```


## Economic and demographic data 
```{r}
##install.packages("gapminder")
library(gapminder)

##install.packages("dplyr")
library(dplyr)

gapminder_2007 <- gapminder %>% filter(year==2007)

ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point()

ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point(alpha=0.5)

ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5)

ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, color = pop) +
  geom_point(alpha=0.8)

ggplot(gapminder_2007) + 
  aes(x = gdpPercap, y = lifeExp, size = pop) +
  geom_point(alpha=0.5)

ggplot(gapminder_2007) + 
  geom_point(aes(x = gdpPercap, y = lifeExp,
                 size = pop), alpha=0.5) + 
  scale_size_area(max_size = 10)

gapminder_1957 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1957) + 
  aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop) +
  geom_point(alpha=0.7) + 
  scale_size_area(max_size = 10) 

gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.7) + 
  scale_size_area(max_size = 10) +
  facet_wrap(~year)
```


## OPTIONAL
```{r}
gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)

gapminder_top5

ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop))

ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = lifeExp)) 

ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop, fill = continent))

ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop, fill = lifeExp))

ggplot(gapminder_top5) +
  aes(x=country, y=pop, fill=gdpPercap) +
  geom_col()

ggplot(gapminder_top5) +
  aes(x=reorder(country, -pop), y=pop, fill=gdpPercap) +
  geom_col()

ggplot(gapminder_top5) +
  aes(x=reorder(country, -pop), y=pop, fill=country) +
  geom_col(col="gray30") +
  guides(fill="none")

head(USArrests)

USArrests$State <- rownames(USArrests)
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_col() +
  coord_flip()

ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_point() +
  geom_segment(aes(x=State, 
                   xend=State, 
                   y=0, 
                   yend=Murder), color="blue") +
  coord_flip()
```